name: GH Docker build and test GPU legate.core

concurrency:
  group: ci-docker-gpu-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "branch-*"

env:
  DOCKER_BUILDKIT: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: legate.core

jobs:
  build-gpu:
    permissions:
      id-token: write # This is required for configure-aws-credentials
      contents: read  # This is required for actions/checkout
      packages: write # This is required to push docker image to ghcr.io

    runs-on: ${{ github.repository == 'nv-legate/legate.core' && 'linux-amd64-cpu4' || 'ubuntu-latest' }}
    steps:
      - name: Checkout legate.core (= this repo)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get AWS credentials for sccache bucket
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-2
          role-duration-seconds: 28800 # 8 hours
          role-to-assume: arn:aws:iam::279114543810:role/gha-oidc-nv-legate

      - name: Build docker image
        run: |
          mkdir -p out conda-build
          docker build \
            --build-arg AWS_SESSION_TOKEN=${{env.AWS_SESSION_TOKEN}} \
            --build-arg AWS_ACCESS_KEY_ID=${{env.AWS_ACCESS_KEY_ID}} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{env.AWS_SECRET_ACCESS_KEY}} \
            --build-arg GITHUB_TOKEN=${{env.GITHUB_TOKEN}} \
            --progress=plain \
            --tag=$IMAGE_NAME \
            --label "git-commit=${{github.sha}}" \
            -f continuous_integration/Dockerfile .
      
      - name: Log in to container image registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=${{github.sha}}

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          
      - name: Display structure of workdir after docker build
        run: ls -R

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "legate.core-gpu-${{ github.sha }}"
          path: |
            conda-build
            out

  test-gpu:
    needs:
      - build-gpu
    runs-on: linux-amd64-gpu-v100-latest-1
    container:
      options: -u root
      image: ghcr.io/nv-legate/legate.core:${{github.sha}}
      # image: rapidsai/devcontainers:23.06-cpp-cuda11.8-mambaforge-ubuntu22.04
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
    steps:
      - name: Run nvidia-smi to make sure GPU is working
        run: nvidia-smi

      - name: Run legate.core unit tests
        shell: su coder {0}
        run: entrypoint run-all-tests