name: Build legate.core on GH

concurrency:
  group: ci-gpu-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"

jobs:
  build:
    permissions: read-all
    # Ref: https://docs.rapids.ai/resources/github-actions/#cpu-labels for `linux-amd64-cpu4`
    runs-on: ${{ github.repository == 'nv-legate/legate.core' && 'linux-amd64-cpu4' || 'ubuntu-latest' }}
    container:
      options: -u root
      image: pauletaylor/devcontainers:23.06-cpp-cuda11.8-mambaforge-ubuntu22.04
      volumes:
        - ${{ github.workspace }}/out:/tmp/out
    steps:
      - name: Checkout legate.core (= this repo)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: legate

      - name: Setup
        shell: bash -eo pipefail {0}
        run: |
          apt update;
          DEBIAN_FRONTEND=noninteractive \
          apt install -y --no-install-recommends \
              numactl rlwrap;

          mv legate/continuous_integration/home/coder/.gitconfig /home/coder/.gitconfig;
          mv legate/continuous_integration/home/coder/.local /home/coder/.local;
          mv legate /home/coder/legate

          chmod a+x /home/coder/.local/bin/*;
          chown -R coder:coder /home/coder/;
          chown -R coder:coder /tmp/out;

      - if: github.repository == 'nv-legate/legate.core'
        name: Get AWS credentials for sccache bucket
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-2
          role-duration-seconds: 14400 # 4 hours
          role-to-assume: arn:aws:iam::279114543810:role/gha-oidc-nv-legate

      - name: Build
        shell: su coder {0}
        run: ~/.local/bin/entrypoint build-all
        env:
          DEFAULT_CONDA_ENV: legate
          PYTHONDONTWRITEBYTECODE: 1
          SCCACHE_REGION: us-east-2
          SCCACHE_BUCKET: rapids-sccache-east
          SCCACHE_S3_KEY_PREFIX: legate-cunumeric-dev
          GH_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}"
          GITHUB_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}"
          VAULT_HOST: "${{ secrets.PERSONAL_ACCESS_TOKEN && 'https://vault.ops.k8s.rapids.ai' || '' }}"
          VAULT_S3_TTL: "14400s" # 4 hours

      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: "legate.core-${{ github.sha }}"
          path: ./out/*
